# **Import Library**

In [16]:
import numpy as np

# **Working Area**

## 1. Buatlah vektor di bawah ini dengan Python

In [17]:
v = np.array([17, 22, 19])
v

array([17, 22, 19])

## 2. Diberikan 3 buah vector 3 dimensi

In [19]:
'''Hitunglah: A+B'''
v_a = v
v_b = np.array([10, 20, 11])
v_c = np.array([5, 12, 9])
print (v_a + v_b)
'''Hitunglah: B-C'''
print (v_b - v_c)
'''Hitunglah: A dot C'''
print (v_a*v_c)
'''Hitunglah: A x B'''
print (v_a@v_b)
'''Hitunglah: norm A'''
print (np.linalg.norm(v_a))
'''Hitunglah: Sudut antara vektor A dan B'''
cos_theta = v_a @ v_b / (np.linalg.norm(v_a) * np.linalg.norm(v_b))
print (cos_theta)


[27 42 30]
[5 8 2]
[ 85 264 171]
819
33.67491648096547
0.9759590023331435


## 3. Buatlah plot dari vector berikut ini kedalam bidang 2D

In [24]:
u = np.array([2,5])
v = np.array([3,1])
z = np.array([[2,5],
              [3,1]])
z

array([[2, 5],
       [3, 1]])